# Generated by Django 3.1.7 on 2021-03-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=500, null=True)),
                ('plowed', models.BooleanField()),
                ('watered', models.BooleanField()),
                ('sulphated', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Parcelle',
            },
        ),
    ]
