language: python
python:
  - '3.8'

# safelist
branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=alea.settings.travis

script:
  - python manage.py test

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITTOKEN
  target_branch: master
  on:
    branch: staging 