# Generated by Django 3.1.7 on 2021-03-03 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('occupation', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employee')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.plot')),
            ],
        ),
    ]
