# Generated by Django 3.1.7 on 2021-03-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210309_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['employee', 'day', 'start']},
        ),
    ]
